# Generated by Django 4.1 on 2022-09-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdId', models.IntegerField()),
                ('ProdImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ProdName', models.CharField(max_length=20)),
                ('ProdPrice', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
