# Generated by Django 4.1 on 2022-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownproject', '0002_productsdisplay_delete_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdisplay',
            name='ProdId',
            field=models.CharField(max_length=20),
        ),
    ]
