# Generated by Django 4.1 on 2022-09-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewProject', '0004_juicesinfo_juiceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='juicesinfo',
            name='JuicePrice',
            field=models.IntegerField(null=True),
        ),
    ]
