# Generated by Django 4.1 on 2022-09-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewProject', '0005_juicesinfo_juiceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='EmailAddress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='LastName',
            field=models.CharField(max_length=50),
        ),
    ]
