# Generated by Django 4.1 on 2022-09-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('AgainPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
