# Generated by Django 4.1 on 2022-09-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_signuppage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginpage',
            name='CnfmPassword',
        ),
    ]
