# Generated by Django 4.1 on 2022-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsales', '0002_alter_foodsales_unitprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsales',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
